apiVersion: v1
kind: Secret
metadata:
  name: catalogapi-secret
type: Opaque
stringData:
  RABBITMQ_USERNAME: fiap
  RABBITMQ_PASSWORD: fiap123
  JWT_KEY: very_secret_demo_key_please_change
  ConnectionStrings__CatalogDb: "Server=sql-catalog,1433;Database=CatalogDb;User Id=sa;Password=StrongPassword!123;TrustServerCertificate=True;"
